audit_header: false
title: "Fort Worth's Best Real Estate Training"
description: Jason Mitchell, a top Real Estate Agent in Fort Worth, shares his/her own internal real estate agent training for free. His/Her Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: #
  - title: Free Strategy Call
    url: /contact/
client:
  name: Jason Mitchell
  title:
  license_number:
  about_markdown: |
    Mitchell Group Real Estate brokered by eXp Realty is a family-owned company built on relationships with our clients, colleagues, and co-workers. We're passionately committed to helping you and your family build a secure future in the home of your dreams. The Mitchell Group has been helping families realize "The American Dream" in the Dallas - Ft. Worth Metroplex since 2006.

    Our goal is to help buyers find the perfect home at the perfect price and sellers sell their homes for top dollar in the shortest amount of time. Our team's proactive and innovative approach to marketing consistently delivers on these goals. As a result, over the last 4 years, we have sold more than 650 homes totaling over $100,000,000.
  market: Fort Worth
  brand: Mitchell Group Real Estate
  brokerage: Keller Williams
  address: 2813 South Hulen Street Suite 150<br>Fort Worth, TX 76109
  phone: 817-896-1874
  phone_type:
  phone2:
  phone2_type:
  email: jason@dfwhomeseeker.com
  url: http://DFWHomeSeeker.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how Mitchell Group Real Estate can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/pages/DFWHomeSeekercom/413708608684287
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/Mitchell-Group/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Fort Worth Real Estate Podcast with Jason Mitchell'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Fort Worth Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Mitchell Group Real Estate - your professional Fort Worth Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Fort Worth, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Jason Mitchell'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Fort Worth Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#c0952d'
  theme_color: '#717075'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#c0952d'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
